Set FinishedSleep via env variable in upgrade tests
Fixes error such as:
Error: test/upgrade/continual/verification.go:81:9: config.FinishedSleep
undefined (type *prober.Config has no field or method FinishedSleep)

* The env variable can be removed once changes from
https://github.com/knative/eventing/pull/6074 are propagated to this
repo.